### ISSUE TITLE
Database file left in project

### ISSUE THREAD

**Issue by wireta** [vicomello/cs50_finalproject#1]
Your database file was not added to .gitignore. It's in the repo. Anyone can access it.

**Comment by justmedev** [comment]
For anyone interested:
This is what the db contains:

<table>
<TR><TH>user_id</TH>
<TH>username</TH>
<TH>hashword</TH>
<TH>email</TH>
</TR>
<TR><TD>1</TD>
<TD>vica</TD>
<TD>pbkdf2:sha256:50000$pCZlYKUs$f9c333687bd93fcd6617e930bc25ee27fd9692b686bb9bf8787782a78b94c0ad</TD>
<TD>NULL</TD>
</TR>
<TR><TD>2</TD>
<TD>teste</TD>
<TD>pbkdf2:sha256:50000$bLvd0Ch3$b949d8ad5d248e602350a76e8cab5e4f80ef9c48c77b4314a2f2c2053e1909bd</TD>
<TD>NULL</TD>
</TR>
<TR><TD>3</TD>
<TD>haha</TD>
<TD>pbkdf2:sha256:50000$dnU3HKqU$c19768e2c150c6390453dcfb1379ed817cc31f8231247b4b8c0a35bf68a24ab1</TD>
<TD>NULL</TD>
</TR>
<TR><TD>4</TD>
<TD>oi</TD>
<TD>pbkdf2:sha256:50000$7VnS8r7l$b78f10666a8d9be103d38aed0a3b9412964e2b3e0a98a62bd56d39e536bc318b</TD>
<TD>NULL</TD>
</TR>
<TR><TD>5</TD>
<TD>aaa</TD>
<TD>pbkdf2:sha256:50000$2pd7l6Qh$72a949dc4412a7f5af030c1ce7a7f05eff83d483120164a936ed399f65746bcc</TD>
<TD>NULL</TD>
</TR>
<TR><TD>6</TD>
<TD>vic</TD>
<TD>pbkdf2:sha256:50000$NoBqVw4b$c796a32dbc18662a823ffd0c5f53bb1cfa5473bb68758bdf52ad9126cac50a48</TD>
<TD>NULL</TD>
</TR>
<TR><TD>7</TD>
<TD>a</TD>
<TD>pbkdf2:sha256:50000$it0uvQUT$5c39eadfce5e9c3864cab6142530ec6c6116c0b0fa04b942443292c8dfa75198</TD>
<TD>NULL</TD>
</TR>
<TR><TD>8</TD>
<TD>b</TD>
<TD>pbkdf2:sha256:50000$G6pubzyc$505ce8894994fff6746bad8766cee449aed12fa235d8b4b6054d16028930feab</TD>
<TD>NULL</TD>
</TR>
<TR><TD>9</TD>
<TD>c</TD>
<TD>pbkdf2:sha256:50000$17R1hAYi$af1483fade588ca6c6a827b9fc3c7bf6f15be6ab9314d30202fb0f08f84e1964</TD>
<TD>NULL</TD>
</TR>
<TR><TD>10</TD>
<TD>d</TD>
<TD>pbkdf2:sha256:50000$ASCgFtta$f7bd39f5dcd57cabcba5c04777264159a2d33b90d955afaa66113911821fe8d0</TD>
<TD>NULL</TD>
</TR>
<TR><TD>11</TD>
<TD>s</TD>
<TD>pbkdf2:sha256:50000$qSlXhztf$c9d5f2f82ba2db0e2fb67a7600d3dcbabb8da6c30dba41e647d3977b458cc559</TD>
<TD>NULL</TD>
</TR>
<TR><TD>12</TD>
<TD>h</TD>
<TD>pbkdf2:sha256:50000$nj76obfm$ec06055c0724425dbded8420bccc7566ec2be87d18a84bd757616c3d03850bb0</TD>
<TD>NULL</TD>
</TR>
<TR><TD>13</TD>
<TD>vicosa</TD>
<TD>pbkdf2:sha256:50000$xvM6NnXj$1a171e9646d15026f0ab0a63004f82c1ba648800355c901eaec5986fc47a2733</TD>
<TD>NULL</TD>
</TR>
<TR><TD>14</TD>
<TD>testinho</TD>
<TD>pbkdf2:sha256:50000$FZftIag6$c7d68aebd7a7895b986bf1d1eb6fe5683b8eca4eb68a493459b22a8e55d28ec2</TD>
<TD>NULL</TD>
</TR>
<TR><TD>15</TD>
<TD>lala</TD>
<TD>pbkdf2:sha256:50000$NEaJ2IDH$b7f3d26ebf489385eb99691b8715dc55c93eb63446bf509f1dfe0f027ee62513</TD>
<TD>lala@gmail.com</TD>
</TR>
<TR><TD>16</TD>
<TD>caca</TD>
<TD>pbkdf2:sha256:50000$UH6APLZJ$1e3d4e4aa706d85499a3b623836dc0180055c1a274852528b1dc8965b7c4acd5</TD>
<TD>caca@gmail.com</TD>
</TR>
<TR><TD>17</TD>
<TD>bb</TD>
<TD>pbkdf2:sha256:50000$Pc8h20Dj$bc5f98fd9c9c02568620e52b76eb666266b55712bd831c0fa04bce7e6de7c65a</TD>
<TD>bb@gmail.com</TD>
</TR>
<TR><TD>18</TD>
<TD>teste1</TD>
<TD>pbkdf2:sha256:50000$li93T4ii$b6d22673b07f2fd699211ac09a13c462bf9f877ba1e8a19b9cf8de05884f6d4e</TD>
<TD>teste1@gmail.com</TD>
</TR>
<TR><TD>19</TD>
<TD>teste2</TD>
<TD>pbkdf2:sha256:50000$fBuEm2FK$e78733a9b9ebf039530022215cd09635b1d7347222def3c323ea4cee8909ee07</TD>
<TD>teste2@gmail.com</TD>
</TR>
<TR><TD>20</TD>
<TD>victoria</TD>
<TD>pbkdf2:sha256:50000$UPYMX5bh$ecc4cf4c382d388272d561dfa79e875fc50f7052ccca58b8becc52996d9e6d1f</TD>
<TD>vic.oldemburgo@gmail.com</TD>
</TR>
<TR><TD>21</TD>
<TD>aline</TD>
<TD>pbkdf2:sha256:50000$jqdg2jPx$742d646ae81b4000aed121841039f811034862768667990d0f75d9b97fcd2555</TD>
<TD>azimerman@college.harvard.edu</TD>
</TR>
<TR><TD>22</TD>
<TD>cacimba</TD>
<TD>pbkdf2:sha256:50000$vQE3ERPT$dd9fd41838c3c278cd1d286ef22f58a38ab23dc9a3b155b1bed598441aeab834</TD>
<TD>a@com</TD>
</TR>
<TR><TD>23</TD>
<TD>vicas</TD>
<TD>pbkdf2:sha256:50000$LeNhVmVy$f5942813e169f72798256f55ab7c5c64b33a78bdf10ecf5c9d634355814c77b0</TD>
<TD>vicas@com</TD>
</TR>
</table>

_Btw I don't think that they'll remove it. Last commit was in 2018_
